# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RoboTalk
email: abigailnhiggins@gmail.com
author: Abigail Higgins
description: >-
  Exploring the intersection of robotics, AI, and the future of technology. 
  Join me on a journey through cutting-edge innovations and technological breakthroughs.
baseurl: "/RoboTalkBlog"
url: "https://abigaillhiggins.github.io"
github_username: abigaillhiggins

# Theme settings
theme_settings:
  # Colors
  primary_color: "#00ff9d"    # Neon green
  accent_color: "#ff00ff"     # Neon pink
  background_color: "#0a0a0a" # Near black
  text_color: "#ffffff"       # White
  
  # Fonts
  heading_font: "'Orbitron', sans-serif"
  body_font: "'Exo 2', sans-serif"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/blog/page:num/"

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/
  posts:
    output: true
    permalink: /posts/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Defaults
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
      comments: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv/
